return {
	-- "stevearc/conform.nvim",
	-- event = { "BufReadPre", "BufNewFile" },
	-- opts = {
	-- 	formatters_by_ft = {
	-- 		lua = { "stylua" },
	-- 		javascript = { "prettierd", "prettier", stop_after_first = true },
	-- 		typescript = { "prettierd", "prettier", stop_after_first = true },
	-- 		javascriptreact = { "prettierd", "prettier", stop_after_first = true },
	-- 		typescriptreact = { "prettierd", "prettier", stop_after_first = true },
	-- 		html = { "prettierd", "prettier", stop_after_first = true },
	-- 		css = { "prettierd", "prettier", stop_after_first = true },
	-- 		yaml = { "prettierd", "prettier", stop_after_first = true },
	-- 		markdown = { "prettierd", "prettier", stop_after_first = true },
	-- 		graphql = { "prettierd", "prettier", stop_after_first = true },
	-- 		svelte = { "prettierd", "prettier", stop_after_first = true },
	-- 		json = { "prettierd", "prettier", stop_after_first = true },
	-- 		jsonc = { "prettierd", "prettier", stop_after_first = true },
	-- 		go = { "goimports", "gofumpt" },
	-- 	},
	-- 	format_on_save = function(bufnr)
	-- 		-- local clients = vim.lsp.get_clients({ bufnr = bufnr })
	-- 		--
	-- 		-- -- organize ts imports
	-- 		-- for _, client in ipairs(clients) do
	-- 		-- 	if client.name == "ts_ls" or client.name == "tsserver" then
	-- 		-- 		if vim.fn.exists(":OrganizeImports") == 2 then
	-- 		-- 			vim.cmd("OrganizeImports")
	-- 		-- 		end
	-- 		-- 		break
	-- 		-- 	end
	-- 		-- end
	--
	-- 		return {
	-- 			lsp_fallback = true,
	-- 			async = false,
	-- 			timeout_ms = 1000,
	-- 		}
	-- 	end,
	-- },
}
