return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	lazy = false,
	auto_update = false,
	dependencies = {
		{ "williamboman/mason.nvim", config = true },
		{ "neovim/nvim-lspconfig" },
	},
	opts = {
		ensure_installed = {
			"lua-language-server",
			"html-lsp",
			"css-lsp",
			"typescript-language-server",
			"tailwindcss-language-server",
			"gopls",
			"elixir-ls",
			"clangd",
			"basedpyright",
			"yaml-language-server",
			"emmet-language-server",
			"eslint-lsp",
			"markdown-oxide",
			"svelte-language-server",
			"prettierd",
			"stylua",
			"gofumpt",
			"clang-format",
			"sql-formatter",
			"goimports",
			"eslint_d",
			"ruff",
			"shfmt",
			-- "checkmake",
		},
	},
}
-- require("lspconfig.ui.windows").default_options.border = "rounded"
